version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: ci

  - package-ecosystem: helm
    directory: "/charts/blocky"
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(blocky)"

  - package-ecosystem: helm
    directory: "/charts/home-assistant"
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(home-assistant)"

  - package-ecosystem: helm
    directory: "/charts/twitch-drops-miner"
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(twitch-drops-miner)"
