version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: deps

  - package-ecosystem: helm
    directory: "/charts/blocky"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(blocky)"

  - package-ecosystem: helm
    directory: "/charts/cloudflare-acme-issuer"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(cloudflare-acme-issuer)"

  - package-ecosystem: helm
    directory: "/charts/home-assistant"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(home-assistant)"

  - package-ecosystem: helm
    directory: "/charts/twitch-drops-miner"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(twitch-drops-miner)"
