{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceMonitor.basicAuth.secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.serviceMonitor.basicAuth.username | quote }}
  password: {{ .Values.serviceMonitor.basicAuth.password | quote }}
{{- end }}
