apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    server: {{ .Values.issuer.acme.server | default "https://acme-v02.api.letsencrypt.org/directory" }}
    email: {{ .Values.issuer.acme.email | default "admin@example.com" }}
    privateKeySecretRef:
      name: {{ .Values.issuer.acme.privateKeySecretName }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.issuer.acme.solver.email | default "admin@example.com" }}
            apiTokenSecretRef:
              name: {{ .Values.issuerSecret.name }}
              key: {{ .Values.issuer.acme.solver.apiTokenSecretKey | default "api-token" }}
