# Manual release counter of shame: 7
apiVersion: v2
name: blocky
description: DNS proxy as ad-blocker for local network
keywords:
  - blocky
  - adblock
  - dns
type: application
version: 1.2.6
appVersion: "v0.29"
