apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-blocky
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
        - name: blocky
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: {{ .Values.config.ports.http }}
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
