apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-blocky"
  annotations:
    metallb.io/loadBalancerIPs: "192.168.4.1,fd77:4595:2dc1:3c65:0:0:4:1"
spec:
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: blocky
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-blocky-http"
  labels:
    app: blocky
    app.kubernetes.io/component: http
spec:
  type: ClusterIP
  selector:
    app: blocky
  ports:
    - name: http
      port: {{ .Values.config.ports.http }}
      targetPort: {{ .Values.config.ports.http }}
      protocol: TCP
