# Manual release counter of shame: 7
apiVersion: v2
name: cloudflare-acme-issuer
description: cert-manager ClusterIssuer for Let's Encrypt DNS-01 via Cloudflare

type: application
version: 1.2.5
appVersion: "1.0.0"
