{{- if and .Values.auth.authentik.enabled .Values.auth.authentik.clientId .Values.auth.authentik.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.authentik.secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.auth.authentik.clientIdKey }}: {{ .Values.auth.authentik.clientId | quote }}
  {{ .Values.auth.authentik.clientSecretKey }}: {{ .Values.auth.authentik.clientSecret | quote }}
{{- end }}
