{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.bearerToken.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceMonitor.bearerToken.secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.serviceMonitor.bearerToken.secretKey }}: {{ .Values.serviceMonitor.bearerToken.token | quote }}
{{- end }}
